import express from "express";
const router = express.Router();
import axios from "axios";
import niceInvoice from "nice-invoice";

router.post("/", async (req, res) => {
  var { name, city, state, total, dealers, address, items } = req.body;
  console.log("body: ", req.body);

  var options = {
    weekday: "long",
    year: "numeric",
    month: "long",
    day: "numeric",
  };

  var currentDate = new Date();

  var billing_date = currentDate.toLocaleDateString("en-US", options);

  var pdfName = `${name}-Invoice.pdf`;

  var due_date = new Date();
  due_date.setDate(due_date.getDate() + 7);
  due_date = due_date.toLocaleDateString("en-US", options);

  var order_number = Math.floor(Math.random() * 899999 + 100000);

  try {
    const invoiceDetail = {
      shipping: {
        name: name,
        address: address,
        city: city,
        state: state,
        country: "Pakistan",
        postal_code: "",
      },
      items: items,
      subtotal: total,
      total: total,
      order_number: order_number,
      header: {
        company_name: "Connect Kissan",
        company_logo: "kisan.png",
        company_address: "Dealers:\n" + dealers,
      },
      footer: {
        text: "Generated by CONNECT KISSAN",
      },
      currency_symbol: "Rs ",
      date: {
        billing_date: billing_date,
        due_date: due_date,
      },
    };
    niceInvoice(invoiceDetail, pdfName);
    res.status(200).json({
      filename: pdfName,
    });
  } catch (error) {
    console.log(error);
    res.status(500).json({
      error: error,
    });
  }
});

router.get("/download/:filename", async (req, res) => {
  console.log(req.params.filename);
  res.download(
    `D://connect-kissan-project//Rajni Project//main-server//${req.params.filename}`
  );
});

export default router;
